import { Difficulty, Exercise } from "@/types/Exercise";

export const exercisesSession001: Exercise[] = [
  {
    id: "ex-001-breathing",
    coach: "Coach Amy",
    title: "Box Breathing Warm-up",
    description:
      "4-in, 4-hold, 4-out, 4-hold. Light diaphragmatic breaths to settle.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "3m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-002-cat-cow",
    coach: "Coach Amy",
    title: "Cat–Cow Spinal Mobility",
    description: "Slow spinal flex/extend within comfort. 8–10 gentle cycles.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "5m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-003-hip-hinge",
    coach: "Coach Amy",
    title: "Hip Hinge Patterning",
    description:
      "Neutral spine, soft knees. Push hips back, maintain rib-to-pelvis stack.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "5m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-004-glute-bridge",
    coach: "Coach Amy",
    title: "Glute Bridge Holds",
    description: "3 sets of 20–30s holds. Focus on even hip extension.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "6m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-005-rest",
    coach: "Coach Amy",
    title: "Rest / Reset",
    description: "Walk, shake out, sip water, gentle nose breathing.",
    difficultyLevel: Difficulty.REST,
    duration: "1m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-006-bird-dog",
    coach: "Coach Amy",
    title: "Bird Dog",
    description:
      "Opposite arm/leg reach, keep pelvis level. 6–8 reps per side, slow.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "6m",
    allocatedSessionId: "session-001",
  },
  {
    id: "ex-007-child-pose",
    coach: "Coach Amy",
    title: "Child’s Pose Cool-down",
    description:
      "Gentle posterior breathing. Relax neck/jaw; broaden lower ribs.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "2m",
    allocatedSessionId: "session-001",
  },
];

export const exercisesSession002: Exercise[] = [
  {
    id: "ex-101-breathing-rib",
    coach: "Coach Amy",
    title: "Rib Expansion Breathing",
    description: "3-count inhale through nose, expand lower ribs; relaxed exhale.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "3m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-102-thoracic-openers",
    coach: "Coach Amy",
    title: "Thoracic Openers (Thread the Needle)",
    description: "6–8 slow reps/side. Keep hips stacked and breath steady.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "5m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-103-hip-hinge-dowel",
    coach: "Coach Amy",
    title: "Hip Hinge with Dowel",
    description: "Dowel along spine, 3-point contact. Smooth hinge, neutral neck.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "6m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-104-glute-bridge-march",
    coach: "Coach Amy",
    title: "Glute Bridge March",
    description: "Hold bridge, alternate marching knees. Control pelvis.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "6m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-105-rest",
    coach: "Coach Amy",
    title: "Rest / Reset",
    description: "Walk, shake out, sip water, gentle nose breathing.",
    difficultyLevel: Difficulty.REST,
    duration: "1m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-106-side-plank-knees",
    coach: "Coach Amy",
    title: "Side Plank (Knees)",
    description: "2–3 sets of 15–25s per side. Long line from ear to knee.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "6m",
    allocatedSessionId: "session-002",
  },
  {
    id: "ex-107-child-pose-reach",
    coach: "Coach Amy",
    title: "Child’s Pose with Reach",
    description: "Reach arms diagonally to bias lats. Breathe into back.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "3m",
    allocatedSessionId: "session-002",
  },
];

export const exercisesSession003: Exercise[] = [
  {
    id: "ex-201-breathing-box-advanced",
    coach: "Coach Amy",
    title: "Box Breathing (5-5-5-5)",
    description: "Even counts. Keep shoulders relaxed; expand ribs 360°.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "4m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-202-cat-cow-prone-pressups",
    coach: "Coach Amy",
    title: "Cat–Cow + Prone Press-ups",
    description: "Gentle cycles then small press-ups, pain-free range.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "6m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-203-hip-hinge-wall-taps",
    coach: "Coach Amy",
    title: "Hinge to Wall Taps",
    description: "Step from wall as able; keep hinge form consistent.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "6m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-204-split-squat-isometric",
    coach: "Coach Amy",
    title: "Split Squat Isometric Holds",
    description: "Short holds mid-range, even weight; keep front knee tracking.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "6m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-205-rest",
    coach: "Coach Amy",
    title: "Rest / Reset",
    description: "Walk, shake out, sip water, gentle nose breathing.",
    difficultyLevel: Difficulty.REST,
    duration: "1m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-206-bird-dog-rows",
    coach: "Coach Amy",
    title: "Bird Dog with Row (Band)",
    description: "Light band, slow row while holding bird dog alignment.",
    difficultyLevel: Difficulty.INTERMEDIATE,
    duration: "6m",
    allocatedSessionId: "session-003",
  },
  {
    id: "ex-207-knees-to-chest-breath",
    coach: "Coach Amy",
    title: "Knees-to-Chest Breath Down",
    description: "Gentle lumbar flexion; slow exhales to reduce tone.",
    difficultyLevel: Difficulty.BEGINNER,
    duration: "3m",
    allocatedSessionId: "session-003",
  },
];
